### PR TITLE
Remove install.php after prelimQuiz installation

### PR DESCRIPTION
**Pull request by LiamNorman**
I created this PR as per issue https://github.com/imujjwal96/prelimQuiz/issues/30

My solution is to use unlink to remove the file once prelimQuiz is installed. 

Let me know what you think or if you have any questions about my approach 👍 

Thanks 😄

### CODE REVIEW

**Comment by LiamNorman** [comment]
I do see that the travis build failed but for an issue unrelated to the PR from what I can see from the log https://travis-ci.org/imujjwal96/prelimQuiz/jobs/280888647

**Comment by imujjwal96** [comment]
Hey, @LiamNorman I tested the changes you made. It is not working! 

About the Travis failure. I checked the logs. You can ignore them!

**Comment by LiamNorman** [comment]
Hey @imujjwal96, I tested it on my local and when I finished using the install.php, it removes the file. Can you see if there is anything in your logs or an error message? Alternatively I'll look at another way to accomplish this 👍

**Comment by LiamNorman** [comment]
Also unlink will remove a file from a folder. I've used it before. The full documentation is here 😄  http://php.net/manual/en/function.unlink.php

**Comment by imujjwal96** [comment]
@LiamNorman As expected, it says permission denied.

    PHP Warning:  unlink(install.php): Permission denied in /home/ujjwalbhardwaj/Websites/prelimquiz/public/install.php on line 107, referer: http://prelimquiz.dev/install.php
 
I think we can approach this as 
> The install.php file should be accessible if the Application/Config/config.php file does not exist. It should be accessible even when the user manually deletes the config file.   

Does this make sense?

**Comment by LiamNorman** [comment]
Hey @imujjwal96, I have made the change. I now check before the script runs if the config file has been generated otherwise I kill the script (if it has been generated).

Let me know what you think :+1:

**Pull request merged**
